### PR TITLE
Update toolchain to 1.75.0

### PR DESCRIPTION
**Pull request by SchmErik**
This PR updates the rust toolchain to `1.75.0` and also includes code that seeds `HashMap` and `HashSet` using `sys_random`.

### CODE REVIEW

**Comment by SchmErik** [comment]
I'll remove the draft mode after sorting out the merge conflicts

**Comment by flaub** [comment]
I'm not sure I can meaningfully review this large number of commits. I wonder if maybe I could do a review of the delta of just our changes. Once that's reviewed then we could do the bump of the `risc0` branch?

**Comment by SchmErik** [comment]
> I'm not sure I can meaningfully review this large number of commits. I wonder if maybe I could do a review of the delta of just our changes. Once that's reviewed then we could do the bump of the `risc0` branch?

Great point! Here's a delta of erik/risc0-1.75.0 and rust's 1.75.0: https://github.com/rust-lang/rust/compare/rust-lang:rust:1.75.0...risc0:rust:erik/risc0-1.75.0

**Comment by SchmErik** [comment]
One interesting change is this this part: https://github.com/rust-lang/rust/compare/rust-lang:rust:1.75.0...risc0:rust:erik/risc0-1.75.0#diff-e014b9a8f5d1cc2cb5074f95f527ae8ef1d47596a64bb32768470304fb1bfa24R48

I basically followed what Weikeng outlined in this issue: https://github.com/risc0/risc0/issues/1275

**Review by flaub — APPROVED** [review]

**Pull request closed without merging**
